tasks:
  - type: docker-build
    image: gabbro-bot
    platform:
      - linux/arm64
    auto:
      - source: push
        has_tag: true
        tag_source: tag
      - source: push
        has_tag: true
        tag_source: latest
    registries:
      - gitlab
